package edu.pdx.cs410J.yl6;

/**
 * This class represent a field validator, which encapsulates the method that
 * takes a string <code>s</code> as argument and determines if <code>s</code>
 * successfully matches some rule defined by <code>isValid</code> method, and
 * generate corresponding error message which can be obtained by client program
 * by invoking <code>getErrorMessage</code> method.
 */
public abstract class AbstractValidator {
    /**
     * Determine if <code>s</code> is valid.
     *
     * @param s the string to be checked.
     * @return <code>true</code> if it is valid; <code>false</code> otherwise.
     */
    public abstract boolean isValid(String s);

    /**
     * Return error message generated by last <code>isValid</code> call.
     *
     * @return error message generated by last <code>isValid</code> call.
     */
    public abstract String getErrorMessage();
}