package edu.pdx.cs410J.yl6;

import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;

public class DateTimeStringValidator extends AbstractValidator {
  
  private String message;
  private String pattern;
  private DateFormat df;

  public DateTimeStringValidator(String pattern) {
    this.pattern = pattern;
    this.df = new SimpleDateFormat(this.pattern);
    this.df.setLenient(false);
  }

  @Override
  public boolean isValid(String s) {
    try {
      df.parse(s);
    } catch (ParseException e) {
      this.message = e.getMessage(); 
      return false;
    }
    return true;
  }

  /**
   * Return error message generated by last <code>isValid</code> call.
   * 
   * @return error message computed during last <code>isValid</code> call.
   */
  @Override
  public String getErrorMessage() {
    return this.message;
  }

}